# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 08:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addr', '0004_auto_20180625_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='addr',
        ),
        migrations.AddField(
            model_name='friend',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friend',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='memo',
        ),
    ]
